apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: isolate-tainted-pods
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      tainted-by-falco: "true"
  ingressDeny:
    - fromEntities: [all]
  egressDeny:
    - toEntities: [all]
