apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-handler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-handler-pod-binding
subjects:
  - kind: ServiceAccount
    name: falco-handler
    namespace: default
roleRef:
  kind: ClusterRole
  name: falco-pod-manager
  apiGroup: rbac.authorization.k8s.io
